services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-app
    ports:
      - "6379:6379"
      - "8001:8001"

  document-database:
    build: .
    container_name: document-database-app
    depends_on:
      - redis-stack
    environment:
      - REDIS_HOST=redis-stack
    entrypoint: ["/entrypoint.sh", "document-database"]

  data-store:
    build: .
    container_name: data-store-app
    depends_on:
      - redis-stack
    environment:
      - REDIS_HOST=redis-stack
    entrypoint: ["/entrypoint.sh", "data-store"]